### ISSUE TITLE
Are the pre-computed values for DNA or RNA?

### ISSUE THREAD

**Issue by kvittingseerup** [Gabaldonlab/crossmapper#1]
And if only DNA could you provide them for RNA as well? Would make my life a lot easier :-)

**Comment by GrantHov** [comment]
Hi @kvittingseerup, thanks for your interest in crossmapper. The pre-computed values are based on DNA simulations. However, crossmapper can work with any input sequences. If you want to simulate RNA-Seq data, for example, you can use RNA mode. In this case, you will need to supply the crossmapper with genome and gtf/gff file (it is our recommended way to simulated RNA-Seq data, see the example 1 in our step-by-step tutorial https://github.com/Gabaldonlab/crossmapper/wiki/Crossmapper-Tutorial). If only a transcriptome is available, you still can run crossmapper, but I suggest to run it in DNA mode, so the software will use bwa mapper instead of STAR (because there is no need of splice-junction detection if you map against the transcriptome). However, fs you simulate and back-map to transcriptome directly, you potentially will miss the reads that cross-map to intergenic regions.   
Hope this helps
